### ISSUE TITLE
Fixing `release.yml` GoReleaser step

### ISSUE THREAD

**Issue by Levistator** [metio/terraform-provider-git#318]
https://github.com/metio/terraform-provider-git/blob/4c062e49bf99ffec8db6bdeaca26722ccc6417be/.github/workflows/release.yml#L52

If you remove this line, I'm pretty sure the effect will be the same as setting it as `latest` 
You will just automatically pick up whatever the `goreleaser/goreleaser-action` default is. 

I was going to push a PR to do it for you but I don't have access and I don't feel like forking it myself for such a simple thing 🤣

**Comment by sebhoss** [comment]
Thanks!
